### ISSUE TITLE
1.19 compatibility

### ISSUE THREAD

**Issue by ghrom** [kirb/iWiki#1]
Any news on 1.19 compatible version, please?

**Comment by kirb** [comment]
Unfortunately I've been busy with other projects lately, but it's definitely coming when I have some time to work on it. Sorry to keep you waiting.

**Comment by kirb** [comment]
I decided to discontinue this project. See [the readme](https://github.com/kirb/iwiki) for details. Sorry to disappoint, I just never needed it or got around to it and to keep this permanently at “will be worked on” would be lying.
